### ISSUE TITLE
Pick a Single Package Manager

### ISSUE THREAD

**Issue by nbibler** [HaulinOats/todo-app#1]
This repository contains both a `yarn.lock` and a `package-lock.json`.

Presumably, the `package-lock.json` was created when the Next.js application was created via `npx create-next-app` and is unused.

Either use `npm` to manage dependencies (via its `package-lock.json`) or `yarn` (via its `yarn.lock`), but not both.

`git rm` the loser. 😉

**Comment by HaulinOats** [comment]
Right, I normally use `npm` so not sure how `yarn` ended up in there. Must have not noticed I used `yarn` to initiate the app instead of using `npx`. Do you prefer `yarn`? I only used it a few times and I know it's generally a lot faster at installing deps than `npm` but any other reasons?
