### ISSUE TITLE
Coding Style Consistency

### ISSUE THREAD

**Issue by nbibler** [HaulinOats/todo-app#4]
Use a [`.editorconfig`](https://editorconfig.org/) and [`prettier`](https://www.npmjs.com/package/prettier) to enforce and automatically correct coding style consistency.

Next.js has documentation for [how to configure prettier](https://nextjs.org/docs/basic-features/eslint#usage-with-other-tools) and have it work well with ESLint. Using the recommended rulesets are generally fine.

VS Code has an [extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) to respect and automatically configure itself based on the Editorconfig settings. Also in VS Code, it's useful to turn on "Format on Save" in projects with prettier enabled... and of course there's an [extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) for that, as well.

**Comment by HaulinOats** [comment]
Yeah, I found out about "Format on Save" in VSCode recently which is pretty nice. I'll make sure to add an `.editorconfig` and install `prettier`.
