### ISSUE TITLE
Prefer Next.js Function Over Argument Typings

### ISSUE THREAD

**Issue by nbibler** [HaulinOats/todo-app#5]
This is mostly a note and not a request for change.

Next.js has relatively good TypeScript definitions, but they're not easy to find and they don't generally use them all in their documentation. Given that, where possible, it's better to use/prefer provided function typings over argument typings when available.

This has the benefit of alerting you and failing if/when the framework or library changes to add/remove/modify arguments or interfaces. It also reduces the number of explicit imports you need to make.

For example:

```diff
diff --git a/pages/api/getTodos.ts b/pages/api/getTodos.ts
index 3bb1d43..ef66ea8 100644
--- a/pages/api/getTodos.ts
+++ b/pages/api/getTodos.ts
@@ -1,11 +1,8 @@
 // Next.js API route support: https://nextjs.org/docs/api-routes/introduction
-import type { NextApiRequest, NextApiResponse } from 'next'
+import type { NextApiHandler } from 'next';
 import type { TodoItem } from '../../types/TodoItem.type';
 
-export default function handler(
-  req: NextApiRequest,
-  res: NextApiResponse<TodoItem[]>
-) {
+const handler: NextApiHandler<TodoItem[]> = (_req, res) => {
   res.status(200).json([
     {
       id: 1,
@@ -28,4 +25,6 @@ export default function handler(
       isCompleted: false
     },
   ])
-}
\ No newline at end of file
+}
+
+export default handler;
```

The underscore on `_req` is in there only because there's a convention to prefix unused arguments with an underscore to acknowledge that it's defined but unused on purpose.

**Comment by HaulinOats** [comment]
Makes sense. I'm new to the NextJS apis and still getting the hang of Typescript, but good to know.
