### ISSUE TITLE
Do Not Mutate Arrays While Iterating

### ISSUE THREAD

**Issue by nbibler** [HaulinOats/todo-app#8]
Less of a concern in this particular implementation (since IDs are presumably unique and there should only be one item with a matching ID), but:

https://github.com/HaulinOats/todo-app/blob/9eb0ce07afc81361417f443b4872c7c6a3b47016/components/TodoList.tsx#L51-L60

This is both iterating and mutating the array. This is bad because the iterator will either have reference to deleted items or the indices will be thrown off (the array contents is changing out from under itself).

Better would be to use `filter` in this particular use case:

```typescript
const deleteTodo = (todoId: number): void => {
  setTodos(
    todos.filter((todo) => todo.id === todoId)
  )
}
```

**Comment by HaulinOats** [comment]
Much simpler. I figured in this particular scenario the return ends the entire loop before any weirdness can occur with additional looping/indexing but I see what you mean about it being a poor way of handling this. Sometimes I forget just how perfectly applicable newer ES6 array methods are in particular scenarios.

Thanks for the feedback!

**Comment by HaulinOats** [comment]
Actually, it would need to filter the elements that DON'T match the id, right?

`todos.filter((todo) => todo.id !== todoId)`

Either way, much cleaner and simpler syntax.
